### Задание 1

In [1]:
import numpy as np

In [6]:
def make_array(max_num):
  return np.arange(max_num-1, -1, -1)

In [7]:
make_array(10)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Задание 2

In [8]:
def make_diag_matrix(max_num):
  return np.diag(make_array(max_num))

In [10]:
def sum_diag_elements(diag_matrix):
  return np.trace(diag_matrix)

In [13]:
make_diag_matrix(5)

array([[4, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0]])

In [14]:
sum_diag_elements(make_diag_matrix(5))

10

### Задание 3

In [20]:
A = np.array([4, 2, 1, 1, 3, 0, 0, 5, 4]).reshape((3,3))
b = np.array([4, 12, -3])
x = np.linalg.solve(A,b)
x

array([ 0.46666667,  3.84444444, -5.55555556])

### Задание 4

In [21]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [26]:
def get_cos_value(vect_1, vect_2):
  vect_1_len = np.linalg.norm(vect_1)
  vect_2_len = np.linalg.norm(vect_2)
    
  return np.dot(vect_1, vect_2) / (vect_1_len * vect_2_len)

In [51]:
def get_closest_customer(users_stats, next_user_stats):
  tmp_array = np.zeros((1, np.shape(users_stats)[0]))
  for i in range(0, np.shape(users_stats)[0]):
    tmp_array[0][i] = get_cos_value(users_stats[i], next_user_stats)
  return np.argmax(tmp_array)+1

In [22]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [52]:
print(f"ID: {get_closest_customer(users_stats, next_user_stats)}")

ID: 8
